version: '3.4'

services:
  dockercp:
    image: dockercp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8081"]
    ports:
      - 8081:8081
      - 5678:5678
    environment:
      - FLASK_APP=app.py
